# Generated by Django 4.1.7 on 2023-03-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='image',
            field=models.ImageField(help_text='Выберите картинку', null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение', width_field=100),
        ),
    ]
