# Generated by Django 4.1.7 on 2023-03-16 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_singer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singer',
            name='image',
        ),
    ]
